swagger: '2.0'
info:
  title: SOTE API
  description: SOTE API
  version: "0.0.1"
schemes:
  - https
basePath: /v1
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /pages:
    get:
      operationId: listPages
      summary: Lists pages
      description: |
        Lists pages
      parameters:
        - name: parentId
          in: query
          description: Filter results by parent id
          required: false
          type: integer
          format: int64
        - name: path
          in: query
          description: Filter results by page path
          required: false
          type: string
        - name: firstResult
          in: query
          description: First result
          required: false
          type: integer
          format: int64
        - name: maxResults
          in: query
          description: Max results
          required: false
          type: integer
          format: int64
      tags:
        - Pages
      responses:
        200:
          description: Returns a list of pages
          schema:
            type: array
            items:
              $ref: '#/definitions/Page'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /pages/{pageId}:
    get:
      operationId: findPage
      summary: Finds page
      description: |
        Finds single page
      parameters:
        - name: pageId
          in: path
          description: page id
          required: true
          type: integer
          format: int64
      tags:
        - Pages
      responses:
        200:
          description: Returns a single page
          schema:
            $ref: '#/definitions/Page'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /pages/{pageId}/content:
    get:
      operationId: findPageContent
      summary: Returns page content in all available languages
      description: |
        Returns single page content in all available languages
      parameters:
        - name: pageId
          in: path
          description: page id
          required: true
          type: integer
          format: int64
      tags:
        - Pages
      responses:
        200:
          description: Returns single page content in all available languages
          schema:
            type: array
            items:
              $ref: '#/definitions/LocalizedValue'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /pages/{pageId}/images:
    get:
      operationId: listPageImages
      summary: Returns a list of page images
      description: |
        Returns a list of page images
      parameters:
        - name: pageId
          in: path
          description: Page id
          required: true
          type: integer
          format: int64
        - name: type
          in: query
          description: Filter by type
          type: string
      tags:
        - Pages
      responses:
        200:
          description: Returns list of page images
          schema:
            type: array
            items:
              $ref: '#/definitions/PageImage'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /pages/{pageId}/images/{imageId}:
    get:
      operationId: findPageImage
      summary: Returns a single page image
      description: |
        Returns a single page image
      parameters:
        - name: pageId
          in: path
          description: Page Id
          required: true
          type: integer
          format: int64
        - name: imageId
          in: path
          description: Page image id
          required: true
          type: integer
          format: int64
      tags:
        - Pages
      responses:
        200:
          description: Returns an page image
          schema:
            $ref: '#/definitions/PageImage'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /pages/{pageId}/images/{imageId}/data:
    get:
      produces:
        - application/octet-stream
      operationId: getPageImageData
      summary: Returns an page image data
      description: |
        Returns an page image data
      parameters:
        - name: pageId
          in: path
          description: Page id
          required: true
          type: integer
          format: int64
        - name: imageId
          in: path
          description: Page image id
          required: true
          type: integer
          format: int64
        - name: size
          in: query
          description: Maximum width or height of image
          required: false
          type: integer
          format: int32
      tags:
        - Pages
      responses:
        200:
          description: Returns an page image data
          schema:
            type: string
            format: binary
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'

definitions:
  Page:
    properties:
      id:
        type: integer
        format: int64
      slug:
        type: string
      title:
        type: array
        items:
          $ref: '#/definitions/LocalizedValue'
  PageImage:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      contentType:
        type: string
      size:
        type: integer
        format: int64
      type:
        type: string
  LocalizedValue: 
    type: object
    properties:
      language:
        type: string
      value:
        type: string
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotImplemented:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
