swagger: '2.0'
info:
  title: SOTE API
  description: SOTE API
  version: "0.0.1"
schemes:
  - https
basePath: /v1
consumes:
  - application/json;charset=utf-8
produces:
  - application/json;charset=utf-8
paths:
  /contents:
    get:
      operationId: listContents
      summary: Lists contents
      description: |
        Lists contents
      parameters:
        - name: parentId
          in: query
          description: Filter results by parent id
          required: false
          type: string
        - name: type
          in: query
          description: Filter results by content type
          required: false
          type: string
          enum:
            - PAGE  
            - NEWS
        - name: firstResult
          in: query
          description: First result
          required: false
          type: integer
          format: int64
        - name: maxResults
          in: query
          description: Max results
          required: false
          type: integer
          format: int64
      tags:
        - Contents
      responses:
        200:
          description: Returns a list of contents
          schema:
            type: array
            items:
              $ref: '#/definitions/Content'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contents/{contentId}:
    get:
      operationId: findContent
      summary: Finds content
      description: |
        Finds single content
      parameters:
        - name: contentId
          in: path
          description: content id
          required: true
          type: integer
          format: int64
      tags:
        - Contents
      responses:
        200:
          description: Returns a single content
          schema:
            $ref: '#/definitions/Content'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contents/{contentId}/content:
    get:
      operationId: findContentData
      summary: Returns content content in all available languages
      description: |
        Returns single content content in all available languages
      parameters:
        - name: contentId
          in: path
          description: content id
          required: true
          type: integer
          format: int64
      tags:
        - Contents
      responses:
        200:
          description: Returns single content content in all available languages
          schema:
            type: array
            items:
              $ref: '#/definitions/LocalizedValue'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contents/{contentId}/images:
    get:
      operationId: listContentImages
      summary: Returns a list of content images
      description: |
        Returns a list of content images
      parameters:
        - name: contentId
          in: path
          description: Content id
          required: true
          type: integer
          format: int64
        - name: type
          in: query
          description: Filter by type
          type: string
      tags:
        - Contents
      responses:
        200:
          description: Returns list of content images
          schema:
            type: array
            items:
              $ref: '#/definitions/ContentImage'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contents/{contentId}/images/{imageId}:
    get:
      operationId: findContentImage
      summary: Returns a single content image
      description: |
        Returns a single content image
      parameters:
        - name: contentId
          in: path
          description: Content Id
          required: true
          type: integer
          format: int64
        - name: imageId
          in: path
          description: Content image id
          required: true
          type: integer
          format: int64
      tags:
        - Contents
      responses:
        200:
          description: Returns an content image
          schema:
            $ref: '#/definitions/ContentImage'
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'
  /contents/{contentId}/images/{imageId}/data:
    get:
      produces:
        - application/octet-stream
      operationId: getContentImageData
      summary: Returns an content image data
      description: |
        Returns an content image data
      parameters:
        - name: contentId
          in: path
          description: Content id
          required: true
          type: integer
          format: int64
        - name: imageId
          in: path
          description: Content image id
          required: true
          type: integer
          format: int64
        - name: size
          in: query
          description: Maximum width or height of image
          required: false
          type: integer
          format: int32
      tags:
        - Contents
      responses:
        200:
          description: Returns an content image data
          schema:
            type: string
            format: binary
        400:
          description: Invalid request was sent to the server
          schema:
            $ref: '#/definitions/BadRequest'
        403:
          description: Attempted to make a call with unauthorized client
          schema:
            $ref: '#/definitions/Forbidden'
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/InternalServerError'

definitions:
  Content:
    properties:
      id:
        type: integer
        format: int64
      parentId:
        type: integer
        format: int64
      slug:
        type: string
      category:
        description: Category slug
        type: string
      type:
        type: string
        description: Content type
        enum:
          - PAGE  
          - NEWS
      title:
        type: array
        items:
          $ref: '#/definitions/LocalizedValue'
  ContentImage:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      contentType:
        type: string
      size:
        type: integer
        format: int64
      type:
        type: string
  LocalizedValue: 
    type: object
    properties:
      language:
        type: string
      value:
        type: string
  InternalServerError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Forbidden:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  BadRequest:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotImplemented:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  NotFound:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
